# Generated by Django 4.2.18 on 2025-02-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemCode', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Code')),
                ('typeOfItem', models.CharField(choices=[('dessert', 'dessert'), ('md', 'md'), ('seasonal', 'seasonal'), ('stock', 'stock'), ('syrup', 'syrup'), ('etc', 'etc')], max_length=30, verbose_name='Type')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('units', models.IntegerField(default=0, verbose_name='Units')),
                ('place', models.CharField(choices=[('창고', '창고'), ('냉장고', '냉장고'), ('냉동고', '냉동고'), ('뒷문', '뒷문'), ('쇼케이스', '쇼케이스'), ('캐비닛', '캐비닛'), ('전시대', '전시대'), ('앞문', '앞문'), ('etc', 'etc')], max_length=30, verbose_name='Place')),
                ('amountOfBulk', models.FloatField(default=0.0, verbose_name='Amount Of Bulk')),
                ('amountOfEach', models.FloatField(default=0.0, verbose_name='Amount of Each')),
                ('lastTimeSaved', models.DateField(auto_now=True, null=True, verbose_name='Last Savetime')),
            ],
        ),
    ]
