# Generated by Django 4.2.18 on 2025-02-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='lastTimeSaved',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Savetime'),
        ),
    ]
