# Generated by Django 4.2.18 on 2025-02-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_item_lasttimesaved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='place',
            field=models.CharField(choices=[('창고', '창고'), ('냉장실', '냉장실'), ('냉동실', '냉동실'), ('뒷문', '뒷문'), ('쇼케이스', '쇼케이스'), ('캐비닛', '캐비닛'), ('전시대', '전시대'), ('앞문', '앞문'), ('etc', 'etc')], max_length=30, verbose_name='Place'),
        ),
    ]
